root = "."

[build]
cmd = "go build -o ./profile ./cmd/profile"
bin = "profile"
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
log = "air.log"
delay = 3 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # nanosecond
rerun = false
rerun_delay = 500

[log]
time = false
main_only = false
silent = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
