volumes:
  go-mod:
  go-build:

services:
  profile:
    build:
      target: base
    volumes:
      - go-mod:/go/pkg/mod
      - go-build:/root/.cache/go-build

      - ${PWD:-.}:${PWD:-/src}
    working_dir: ${PWD:-/src}
    entrypoint: [ go, run, ./cmd ]